# Generated by Django 4.0.5 on 2022-06-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='username',
        ),
    ]
